"""
AlienVault OTX Threat Intelligence Updater

Fetches IOCs from AlienVault Open Threat Exchange and saves to otx_data.json.

Usage:
    python3 update_otx.py

Requires:
    OTX_API_KEY set in .env (get one at https://otx.alienvault.com)
    or passed via OTX_API_KEY environment variable.

Runs standalone — can be called from cron/systemd timer.
"""

import json
import logging
import os
import sys
from datetime import datetime, timezone

import requests
from dotenv import load_dotenv

for env_path in [
    "/home/aiagent/mission-control-site/.env",
    os.path.join(os.path.dirname(__file__), ".env"),
]:
    if os.path.exists(env_path):
        load_dotenv(env_path)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [OTX] %(message)s")
log = logging.getLogger("otx")

OTX_API_KEY = os.getenv("OTX_API_KEY", "").strip()
OTX_DATA_FILE = os.path.join(os.path.dirname(__file__), "otx_data.json")
TIMEOUT = 30


def fetch_events() -> list:
    pulses = []
    url = "https://otx.alienvault.com/api/v1/pulses/subscribed"
    headers = {"X-OTX-API-KEY": OTX_API_KEY}
    params = {"limit": 20, "page": 1}

    for page in range(1, 4):
        params["page"] = page
        try:
            resp = requests.get(url, headers=headers, params=params, timeout=TIMEOUT)
            if resp.status_code == 403:
                log.error("OTX API returned 403 — check your API key")
                return pulses
            if resp.status_code == 429:
                log.warning("OTX API rate limited, stopping fetch")
                break
            resp.raise_for_status()
            data = resp.json()
            results = data.get("results", [])
            if not results:
                break
            pulses.extend(results)
        except requests.Timeout:
            log.warning("OTX API timeout on page %d", page)
            break
        except requests.RequestException as e:
            log.error("OTX API error: %s", e)
            break

    log.info("Fetched %d pulses from OTX", len(pulses))
    return pulses


def extract_iocs(pulses: list) -> dict:
    ips = set()
    domains = set()
    hashes = set()
    urls = set()

    for pulse in pulses:
        iocs = pulse.get("indicators", [])
        for ioc in iocs:
            ioc_type = (ioc.get("type") or "").upper()
            indicator = (ioc.get("indicator") or "").strip()
            if not indicator:
                continue
            if ioc_type in ("IPv4", "IP", "IPV4"):
                ips.add(indicator)
            elif ioc_type in ("DOMAIN", "HOSTNAME"):
                domains.add(indicator)
            elif ioc_type in ("MD5", "SHA1", "SHA256", "FILEHASH-MD5", "FILEHASH-SHA1", "FILEHASH-SHA256"):
                hashes.add(indicator)
            elif ioc_type == "URL":
                urls.add(indicator)

    return {
        "ips": sorted(ips),
        "domains": sorted(domains),
        "hashes": sorted(hashes),
        "urls": sorted(urls),
        "total_iocs": len(ips) + len(domains) + len(hashes) + len(urls),
    }


def generate_wazuh_rules(iocs: dict) -> str:
    lines = [
        "<!--",
        "  Wazuh Threat Intelligence Rules – Auto-generated by Mission Control OTX Updater",
        f"  Generated: {datetime.now(timezone.utc).isoformat()}",
        f"  Total IOCs: {iocs['total_iocs']}",
        "  Note: These are example rules. Deploy to /var/ossec/etc/rules/ on your Wazuh manager.",
        "  Rule IDs 100000-100999 are reserved for local/custom rules.",
        "-->",
        '<group name="otx_threat_intel,">',
        "",
    ]

    rule_id = 100000
    for ip in iocs["ips"]:
        rule_id += 1
        lines.extend([
            f'<rule id="{rule_id}" level="12">',
            f'  <if_sid>80700</if_sid>',
            f'  <field name="srcip">{ip}</field>',
            f'  <description>OTX Threat Intel: Malicious IP {ip}</description>',
            f'  <group>otx_threat_intel,</group>',
            f'</rule>',
            "",
        ])

    for domain in iocs["domains"]:
        rule_id += 1
        lines.extend([
            f'<rule id="{rule_id}" level="12">',
            f'  <if_sid>80700</if_sid>',
            f'  <field name="domain_name">{domain}</field>',
            f'  <description>OTX Threat Intel: Malicious Domain {domain}</description>',
            f'  <group>otx_threat_intel,</group>',
            f'</rule>',
            "",
        ])

    for h in iocs["hashes"]:
        rule_id += 1
        lines.extend([
            f'<rule id="{rule_id}" level="12">',
            f'  <if_sid>80700</if_sid>',
            f'  <field name="file_hash">{h}</field>',
            f'  <description>OTX Threat Intel: Malicious File Hash {h[:16]}...</description>',
            f'  <group>otx_threat_intel,</group>',
            f'</rule>',
            "",
        ])

    lines.append('</group>')
    return "\n".join(lines)


def update():
    if not OTX_API_KEY:
        log.warning("OTX_API_KEY not set — update skipped. Set it in .env to enable threat intel.")
        default = {
            "enabled": False,
            "total_iocs": 0,
            "ips": 0,
            "domains": 0,
            "hashes": 0,
            "size_bytes": 0,
            "last_updated": None,
            "message": "Configure OTX_API_KEY in .env and run python3 update_otx.py to enable AlienVault OTX threat intelligence.",
        }
        with open(OTX_DATA_FILE, "w") as f:
            json.dump(default, f, indent=2)
        log.info("Written %s (disabled)", OTX_DATA_FILE)
        return default

    pulses = fetch_events()
    iocs = extract_iocs(pulses)
    now = datetime.now(timezone.utc).isoformat()

    rules_xml = generate_wazuh_rules(iocs)
    rules_path = os.path.join(os.path.dirname(__file__), "otx_rules.xml")
    with open(rules_path, "w") as f:
        f.write(rules_xml)

    ioc_list = []
    for ip in iocs["ips"]:
        ioc_list.append({"type": "ip", "value": ip, "category": "malicious_ip"})
    for domain in iocs["domains"]:
        ioc_list.append({"type": "domain", "value": domain, "category": "malicious_domain"})
    for h in iocs["hashes"]:
        fmt = "sha256" if len(h) == 64 else "sha1" if len(h) == 40 else "md5"
        ioc_list.append({"type": fmt, "value": h, "category": "malicious_hash"})
    for url in iocs["urls"]:
        ioc_list.append({"type": "url", "value": url, "category": "malicious_url"})

    total = iocs["total_iocs"]
    data = {
        "enabled": True,
        "total_iocs": total,
        "pulse_count": len(pulses),
        "ips": len(iocs["ips"]),
        "domains": len(iocs["domains"]),
        "hashes": len(iocs["hashes"]),
        "urls": len(iocs["urls"]),
        "size_bytes": len(rules_xml.encode("utf-8")),
        "last_updated": now,
        "rules_file": "otx_rules.xml",
        "message": f"OTX threat intel active — {total} IOCs from {len(pulses)} pulses.",
        "iocs": ioc_list,
    }

    with open(OTX_DATA_FILE, "w") as f:
        json.dump(data, f, indent=2)

    log.info("Written %s (%d IOCs, %d bytes rules)", OTX_DATA_FILE, total, data["size_bytes"])
    return data


if __name__ == "__main__":
    result = update()
    print(json.dumps(result, indent=2))
